# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

check_names <- function(x, column_count) {
    .Call('_DoordaHostSDK_check_names', PACKAGE = 'DoordaHostSDK', x, column_count)
}

transpose <- function(input, output) {
    .Call('_DoordaHostSDK_transpose', PACKAGE = 'DoordaHostSDK', input, output)
}

